export const supportedLanguages = [
	{ title: 'None / Plaintext' },
	// { key: 'abap', title: 'ABAP' },
	// { key: 'apex', title: 'Apex' },
	// { key: 'azcli', title: 'Azure CLI' },
	{ key: 'bat', title: 'Batch' },
	// { key: 'bicep', title: 'Bicep' },
	// { key: 'cameligo', title: 'Cameligo' },
	{ key: 'clojure', title: 'Clojure' },
	{ key: 'coffeescript', title: 'CoffeeScript' },
	{ key: 'c', title: 'C' },
	{ key: 'cpp', title: 'C++' },
	{ key: 'csharp', title: 'C#' },
	// { key: 'csp', title: 'CSP' },
	{ key: 'css', title: 'CSS' },
	{ key: 'cypher', title: 'OpenCypher' },
	{ key: 'dart', title: 'Dart' },
	{ key: 'dockerfile', title: 'Dockerfile' },
	// { key: 'ecl', title: 'ECL' },
	{ key: 'elixir', title: 'Elixir' },
	// { key: 'flow9', title: 'Flow9' },
	// { key: 'freemarker2', title: 'FreeMarker2' },
	// { key: 'freemarker2.tag-angle.interpolation-bracket', title: 'FreeMarker2 (Angle/Bracket)' },
	// { key: 'freemarker2.tag-angle.interpolation-dollar', title: 'FreeMarker2 (Angle/Dollar)' },
	// { key: 'freemarker2.tag-bracket.interpolation-bracket', title: 'FreeMarker2 (Bracket/Bracket)' },
	// { key: 'freemarker2.tag-bracket.interpolation-dollar', title: 'FreeMarker2 (Bracket/Dollar)' },
	// { key: 'freemarker2.tag-auto.interpolation-bracket', title: 'FreeMarker2 (Auto/Bracket)' },
	// { key: 'freemarker2.tag-auto.interpolation-dollar', title: 'FreeMarker2 (Auto/Dollar)' },
	{ key: 'fsharp', title: 'F#' },
	{ key: 'go', title: 'Go' },
	{ key: 'graphql', title: 'GraphQL' },
	{ key: 'handlebars', title: 'Handlebars' },
	// { key: 'hcl', title: 'Terraform / HCL' },
	{ key: 'html', title: 'HTML / XHTML' },
	{ key: 'ini', title: 'Ini' },
	{ key: 'java', title: 'Java' },
	{ key: 'javascript', title: 'JavaScript' },
	{ key: 'julia', title: 'Julia' },
	{ key: 'kotlin', title: 'Kotlin' },
	{ key: 'less', title: 'Less' },
	// { key: 'lexon', title: 'Lexon' },
	// { key: 'liquid', title: 'Liquid' },
	{ key: 'lua', title: 'Lua' },
	// { key: 'm3', title: 'Modula3' },
	{ key: 'markdown', title: 'Markdown' },
	{ key: 'mips', title: 'MIPS / MIPS-V' },
	// { key: 'msdax', title: 'DAX / MSDAX' },
	{ key: 'mysql', title: 'MySQL' },
	{ key: 'objective-c', title: 'Objective-C' },
	{ key: 'pascal', title: 'Pascal' },
	{ key: 'pascaligo', title: 'Pascaligo' },
	{ key: 'perl', title: 'Perl' },
	{ key: 'pgsql', title: 'PostgreSQL' },
	{ key: 'php', title: 'PHP' },
	// { key: 'postiats', title: 'ATS/Postiats' },
	// { key: 'powerquery', title: 'Power Query' },
	{ key: 'powershell', title: 'PowerShell' },
	{ key: 'proto', title: 'Protocol Buffers' },
	{ key: 'pug', title: 'Pug / Jade' },
	{ key: 'python', title: 'Python' },
	// { key: 'qsharp', title: 'Q#' },
	{ key: 'r', title: 'R' },
	{ key: 'razor', title: 'Razor' },
	{ key: 'redis', title: 'Redis' },
	// { key: 'redshift', title: 'Redshift' },
	// { key: 'restructuredtext', title: 'reStructuredText' },
	{ key: 'ruby', title: 'Ruby' },
	{ key: 'rust', title: 'Rust' },
	{ key: 'sb', title: 'Small Basic' },
	{ key: 'scala', title: 'Scala / SBT / Dotty' },
	// { key: 'scheme', title: 'Scheme' },
	{ key: 'scss', title: 'SCSS / SASS' },
	{ key: 'shell', title: 'Shell' },
	{ key: 'sol', title: 'Solidity' },
	{ key: 'logs', title: 'Logs' },
	// { key: 'aes', title: 'Sophia' },
	// { key: 'sparql', title: 'SPARQL' },
	{ key: 'sql', title: 'SQL' },
	// { key: 'st', title: 'StructuredText' },
	{ key: 'swift', title: 'Swift' },
	// { key: 'systemverilog', title: 'SystemVerilog' },
	// { key: 'verilog', title: 'Verilog' },
	// { key: 'tcl', title: 'Tcl/Tk' },
	// { key: 'twig', title: 'Twig' },
	{ key: 'typescript', title: 'TypeScript' },
	{ key: 'vb', title: 'Visual Basic' },
	{ key: 'xml', title: 'XML' },
	{ key: 'yaml', title: 'YAML' },
];
