export type SupportedLanguagesKey = NonNullable<(typeof supportedLanguages)[number]['key']>;

export const supportedLanguages = [
	{ key: undefined, title: 'None / Plaintext', extensions: undefined },
	{ key: 'bat', title: 'Batch', extensions: ['bat'] },
	{ key: 'clojure', title: 'Clojure', extensions: ['clj'] },
	{ key: 'coffeescript', title: 'CoffeeScript', extensions: ['coffee'] },
	{ key: 'c', title: 'C', extensions: ['c', 'h'] },
	{ key: 'cpp', title: 'C++', extensions: ['cpp', 'cc'] },
	{ key: 'csharp', title: 'C#', extensions: ['cs'] },
	{ key: 'css', title: 'CSS', extensions: ['css'] },
	{ key: 'dart', title: 'Dart', extensions: ['dart'] },
	{ key: 'dockerfile', title: 'Dockerfile', extensions: ['Dockerfile'] },
	{ key: 'elixir', title: 'Elixir', extensions: ['ex', 'exs'] },
	{ key: 'fsharp', title: 'F#', extensions: ['f'] },
	{ key: 'go', title: 'Go', extensions: ['go'] },
	{ key: 'graphql', title: 'GraphQL', extensions: ['graphql', 'gql', 'graphqls'] },
	{ key: 'handlebars', title: 'Handlebars', extensions: ['hbs'] },
	{ key: 'html', title: 'HTML / XHTML', extensions: ['html', 'mhtml', 'htm'] },
	{ key: 'ini', title: 'Ini', extensions: ['ini'] },
	{ key: 'java', title: 'Java', extensions: ['java'] },
	{ key: 'javascript', title: 'JavaScript', extensions: ['js', 'jsx'] },
	{ key: 'julia', title: 'Julia', extensions: ['jl'] },
	{ key: 'kotlin', title: 'Kotlin', extensions: ['kt'] },
	{ key: 'less', title: 'Less', extensions: ['less'] },
	{ key: 'lua', title: 'Lua', extensions: ['lua'] },
	{ key: 'markdown', title: 'Markdown', extensions: ['md'] },
	{ key: 'objective-c', title: 'Objective-C', extensions: ['m'] },
	{ key: 'pascal', title: 'Pascal', extensions: ['lpi', 'lpr', 'pp', 'pas', 'lfm'] },
	{ key: 'perl', title: 'Perl', extensions: ['pl'] },
	{ key: 'pgsql', title: 'PostgreSQL', extensions: ['sql'] },
	{ key: 'php', title: 'PHP', extensions: ['php'] },
	{ key: 'powershell', title: 'PowerShell', extensions: ['ps'] },
	{ key: 'proto', title: 'Protocol Buffers', extensions: ['proto'] },
	{ key: 'pug', title: 'Pug / Jade', extensions: ['pug'] },
	{ key: 'python', title: 'Python', extensions: ['py'] },
	{ key: 'r', title: 'R', extensions: ['r'] },
	{ key: 'razor', title: 'Razor', extensions: ['razor'] },
	{ key: 'ruby', title: 'Ruby', extensions: ['rb'] },
	{ key: 'rust', title: 'Rust', extensions: ['rs'] },
	{ key: 'scala', title: 'Scala / SBT / Dotty', extensions: ['scala'] },
	{ key: 'scss', title: 'SCSS / SASS', extensions: ['scss'] },
	{ key: 'shell', title: 'Shell', extensions: ['sh', 'bash'] },
	{ key: 'sol', title: 'Solidity', extensions: ['sol'] },
	{ key: 'logs', title: 'Logs', extensions: ['logs'] },
	{ key: 'sql', title: 'SQL', extensions: ['sql'] },
	{ key: 'swift', title: 'Swift', extensions: ['swift'] },
	{ key: 'typescript', title: 'TypeScript', extensions: ['ts', 'tsx'] },
	{ key: 'vb', title: 'Visual Basic', extensions: ['vb', 'vbs'] },
	{ key: 'xml', title: 'XML', extensions: ['xml'] },
	{ key: 'yaml', title: 'YAML', extensions: ['yml', 'yaml'] },
] as const;
